config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: "users/sessions",
                                   registrations: "users/registrations",
                                   confirmations: "users/confirmations",
                                   passwords: "users/passwords",
                                   unlocks: "users/unlocks"
                   }

  resources :resumes

  get 'about' => 'static_pages#about', as: :about

  get 'contact' => 'static_pages#contact', as: :contact

  get 'pricing' => 'static_pages#pricing', as: :pricing

  get 'profile' => 'users#profile', as: :current_user

  root 'static_pages#home'

end

app/views/shared/_flashes.erb
<div class="container">
  <% flash.each do |type, message| %>
      <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= message %>
      </div>
  <% end %>
</div>

app/views/shared/_footer.erb
<section id="footer">
  <footer class="footer">
    <div class="container-fluid">
      <p class="text-muted">Resumisto</p>
    </div>
  </footer>
</section>

app/views/shared/_static_navbar.erb
<section id="header">


  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Resumisto', root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign In',  :new_user_session unless current_user %></li>
          <li><%= link_to 'Sign Out',  :destroy_user_session, method: :delete if current_user %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown
              <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

</section>