config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: "users/sessions",
                                   registrations: "users/registrations",
                                   confirmations: "users/confirmations",
                                   passwords: "users/passwords",
                                   unlocks: "users/unlocks"
                   }

  resources :resumes

  get 'about' => 'static_pages#about', as: :about

  get 'contact' => 'static_pages#contact', as: :contact

  get 'pricing' => 'static_pages#pricing', as: :pricing

  get 'profile' => 'users#profile', as: :current_user

  root 'static_pages#home'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessor :resume_file
  belongs_to :user
  before_save :upload_file

  private
  def upload_file
    azure_blob_service = Azure::BlobService.new
    content = resume_file.read
    name = SecureRandom.hex
    result = azure_blob_service.create_block_blob(AZURE_CONTAINER, name , content)
    self.url = result.name
  end


end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)
    @resume.user_id = current_user.id if current_user
    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:name, :description, :resume_file)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>


    </div>
  <% end %>

  <div class="actions">
    Name: <%= f.text_field :name %><br />
    Description: <%= f.text_field :description %><br />
    Resume file: <%= f.file_field  :resume_file %>
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<div class="container-fluid">
  <h1>Editing Resume</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @resume %> |
  <%= link_to 'Back', resumes_path %>


</div>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resumes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<div class="container-fluid">
  <h1>New Resume</h1>



  <%= render 'form' %>

  <%= link_to 'Back', resumes_path %>
</div>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @resume.name %>
</p>
<p>
  <%= link_to 'Resume', "https://resumistodev.blob.core.windows.net/develop/" + @resume.url %>
</p>
<p>
  <%= @resume.user.email %>
</p>



<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>